blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogapp.urls')),
    
]

if settings.DEBUG:  
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about-me/', views.about_me, name='about-me'),
    path('recent-posts/', views.recent_posts, name='recent-posts'),
    path('add-posts/',views.add_post,name='add-post'),
    path('reading/<id>', views.reading, name = "reading"),
    path('edit/<id>', views.edit, name='edit'),
    path('delete/<id>', views.delete, name='delete'),
]

blogapp/models.py
from django.db import models

# Create your models here.
class AddPost(models.Model):
    title = models.CharField(max_length=225)
    description = models.TextField()
    image = models.ImageField(upload_to='img/')
    created_at = models.DateTimeField(auto_now_add=True)
    

blogapp/forms.py
from django import forms
from .models import AddPost

class AddPostForm(forms.ModelForm):
    class Meta:
        model = AddPost
        fields = ['title', 'description', 'image']

blogapp/views.py
from django.shortcuts import render,redirect
from .forms import AddPostForm
from .models import AddPost

def index(request):
    posts = AddPost.objects.all()
    return render(request, 'index.html', {'posts': posts})

def about_me(request):
    return render(request, 'about-me.html')

def recent_posts(request):
    posts = AddPost.objects.all()
    return render(request, 'recent-posts.html', {'posts': posts})

def add_post(request):
    if request.method == 'POST':
        form = AddPostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('index')  
    else:
        form = AddPostForm()
    return render(request,'add-post.html',{'form': form})

from django.shortcuts import render

def reading(request,id):
    post = AddPost.objects.get(id=id)
    return render(request, 'reading.html', {'post' : post})

def edit(request,id):
    post = AddPost.objects.get(id=id)
    if request.method == 'POST':
        form = AddPostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = AddPostForm(instance=post)
    return render(request, 'edit.html', {'form': form, 'post': post})

def delete(request,id):
    post = AddPost.objects.get(id=id)
    post.delete()
    return redirect('index')  
        

templates/about-me.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<header>
    <div class="container container-flex">
        <div class="site-title">
            <h1>Living the social life</h1>
            <p class="subtitle">A blog exploring minimalism in life</p>
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a class="current-page" href="{% url 'about-me' %}">About me</a></li>
                <li><a href="{% url 'add-post' %}">Add post</a></li>
                <li><a href="{% url 'recent-posts' %}">Recent posts</a></li>
            </ul>
        </nav>
    </div> <!-- / .container -->
</header>

<div class="container container-flex">
    <main role="main">
        <img src="{% static 'img/about-me.jpg' %}" class="image-full">
        <h2>My name is John and living the simple life saved my life</h2>

        <p><strong>I used to be a pack rat</strong>. I had so many things that I thought that I loved, but the truth was
            I couldn't even appreciate any of it because there was too much.</p>
        <p>Things were terrible. I had a job that I hated, a home that I didn't want to live in, and I couldn't hold a
            relationship.</p>

        <h3>How I turned things around</h3>
        <p><strong>I was on the verge of a breakdown when I got rid of everything</strong>. I literally put 90% of my
            possessions in the garbage, sold my place and moved into a smaller apartment, and I quit my job.</p>
        <p>It wasn't easy at all, but everything around me was in such a bad place, I didn't know what else to do. And
            it worked.</p>

        <h3>Now I live the simple life</h3>
        <p>Now that I'm living a simple life, things are so much better. I'm less stressed, enjoy life and work more,
            and I have more free time to enjoy.</p>
        <p>With how much it turned my life around, <strong>I felt like I had no choice but to start sharing how I did
                it</strong>, and how others can benefit from living a simple life as well, which is why I started this
            site!</p>
    </main>

    <aside class="sidebar">

        <div class="sidebar-widget">
            <h2 class="widget-title">RECENT POSTS</h2>
            <div class="widget-recent-post">
                <h3 class="widget-recent-post-title">Keeping cooking simple</h3>
                <img src="{% static 'img/food.jpg' %}" alt="two dumplings on a wood plate with chopsticks" class="widget-image">
            </div>
            <div class="widget-recent-post">
                <h3 class="widget-recent-post-title">Simplicity and work</h3>
                <img src="{% static 'img/work.jpg' %}" alt="a chair white chair at a white desk on a white wall" class="widget-image">
            </div>
            <div class="widget-recent-post">
                <h3 class="widget-recent-post-title">Simple decorations</h3>
                <img src="{% static 'img/deco.jpg' %}" alt="a green plant in a clear, round vase with water in it"
                    class="widget-image">
            </div>
        </div>

    </aside>

</div>


<footer>
    <p><strong>Living the Simple Life</strong></p>
    <p>Copyright 2019</p>
</footer>


{% endblock %}

templates/add-post.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<header>
    <div class="container container-flex">
        <div class="site-title">
            <h1>Living the social life</h1>
            <p class="subtitle">A blog exploring minimalism in life</p>
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'about-me' %}">About me</a></li>
                <li><a class="current-page" href="{% url 'add-post' %}">Add post</a></li>
                <li><a href="{% url 'recent-posts' %}">Recent posts</a></li>
            </ul>
        </nav>
    </div> <!-- / .container -->
</header>
<div class="form_div">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="center-btn">
            <button type="submit">Submit</button>
        </div>
    </form>
</div>

<footer>
    <p><strong>Living the Simple Life</strong></p>
    <p>Copyright 2019</p>
</footer>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <link href="https://fonts.googleapis.com/css?family=Lora|Ubuntu:300,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    {% block content %}

    {% endblock %}
</body>
</html>

templates/edit.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<header>
    <div class="container container-flex">
        <div class="site-title">
            <h1>Living the social life</h1>
            <p class="subtitle">A blog exploring minimalism in life</p>
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'about-me' %}">About me</a></li>
                <li><a class="current-page" href="{% url 'add-post' %}">Add post</a></li>
                <li><a href="{% url 'recent-posts' %}">Recent posts</a></li>
            </ul>
        </nav>
    </div> <!-- / .container -->
</header>
<div class="form_div">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}        
        <div class="mb-3 d-flex w-100">
            <label for="id_title" class="form-label">Title</label>
            {{ form.title }}
        </div>
        <div class="mb-3 d-flex w-100" >
            <label for="id_description" class="form-label">Description</label>
            {{ form.description }}
        </div>        
        {% if form.instance.image %}
            <div class="mb-3 d-flex w-100">
                <label class="form-label"><strong>Current Image:</strong></label>
                <div>
                    <img src="{{ form.instance.image.url }}" alt="Current image" class="img-fluid " style="max-width: 280px; max-height: 300px;">
                </div>
            </div>
        {% endif %}
        <div class="mb-3 d-flex w-100">
            <label for="id_image" class="form-label"><strong>Change Image:</strong></label>
            <input type="file" class="form-control" id="id_image" name="image">
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Save Changes</button>
        </div>
    </form>
</div>

<footer>
    <p><strong>Living the Simple Life</strong></p>
    <p>Copyright 2019</p>
</footer>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<header>
    <div class="container container-flex">
        <div class="site-title">
            <h1>Living the social life</h1>
            <p class="subtitle">A blog exploring minimalism in life</p>
        </div>
        <nav>
            <ul>
                <li><a class="current-page" href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'about-me' %}">About me</a></li>
                <li><a href="{% url 'add-post' %}">Add post</a></li>
                <li><a href="{% url 'recent-posts' %}">Recent posts</a></li>                
            </ul>
        </nav>
    </div> <!-- / .container -->
</header>

<div class="container container-flex">
    <main role="main">
        <article class="article-featured">
            <img src="{% static 'img/life.jpg' %}" alt="simple white desk on a white wall with a plant on the far right side" class="article-image">
        </article>
        {% for post in posts %}
        <article class="article-recent">
            <div class="article-recent-main">
                <h2 class="article-title">{{ post.title }}</h2>
                <p class="article-body">{{ post.description|truncatewords:30 }}</p>
                <a href="{% url 'reading' post.id %}" class="article-read-more">CONTINUE READING</a>
            </div>
            <div class="article-recent-secondary">
                <img src="{{ post.image.url }}" alt="image related to {{ post.title }}" class="article-image">
                <p class="article-info">{{ post.created_at|date:"F j, Y" }}</p>
            </div>
        </article>
        {% endfor %}
        
        
        
    </main>
    <aside class="sidebar">
        <div class="sidebar-widget">
            <h2 class="widget-title">ABOUT ME</h2>
            <img src="{% static 'img/about-me.jpg' %}" alt="john doe" class="widget-image">
            <p class="widget-body">I find life better, and I'm happier, when things are nice and simple.</p>
        </div>
    </aside>
</div>

<footer>
    <p><strong>Living the Simple Life</strong></p>
    <p>Copyright 2019</p>
</footer>
{% endblock %}

templates/reading.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<header>
    <div class="container container-flex">
        <div class="site-title">
            <h1>Living the social life</h1>
            <p class="subtitle">A blog exploring minimalism in life</p>
        </div>
        <nav>
            <ul>
                <li><a class="current-page" href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'about-me' %}">About me</a></li>
                <li><a href="{% url 'add-post' %}">Add post</a></li>
                <li><a href="{% url 'recent-posts' %}">Recent posts</a></li>
            </ul>
        </nav>
    </div> <!-- / .container -->
</header>

<article class="article-recent">
    <div class="article-recent-main">
        <h2 class="article-title">{{ post.title }}</h2>
        <p class="article-body">{{ post.description|truncatewords:30 }}</p> 
        <div>
            <a href="{% url 'edit' post.id %}"><button class="edit_btn">Edit</button></a>
            <a href="{% url 'delete' post.id %}"><button class="delete_btn">Delete</button></a>            
        </div>       
    </div>
    <div class="article-recent-secondary">
        <img src="{{ post.image.url }}" alt="image related to {{ post.title }}" class="article-image" style="margin-bottom: 29px;">        
    </div>
</article>


<footer>
    <p><strong>Living the Simple Life</strong></p>
    <p>Copyright 2019</p>
</footer>

{% endblock %}

templates/recent-posts.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<header>
    <div class="container container-flex">
        <div class="site-title">
            <h1>Living the social life</h1>
            <p class="subtitle">A blog exploring minimalism in life</p>
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'about-me' %}">About me</a></li>
                <li><a href="{% url 'add-post' %}">Add post</a></li>
                <li><a class="current-page" href="{% url 'recent-posts' %}">Recent posts</a></li>
            </ul>
        </nav>
    </div> <!-- / .container -->
</header>

<div class="container container-flex">
    <main role="main">

        <article class="article-recent">
            <div class="article-recent-main">
                <h2 class="article-title">Finding simplicity in life</h2>
                <p class="article-body"><strong>Life can get complicated really quickly</strong>, but it doesn't have to
                    be! There are many ways to simplify your life, <a href="#">a few of which we've explored in the
                        past</a>. This week we're taking a bit of a approach though, in how you can find simplicity in
                    the life you already living.</p>
                <a href="#" class="article-read-more">CONTINUE READING</a>
            </div>
            <div class="article-recent-secondary">
                <img src="{% static 'img/life.jpg' %}"
                    alt="simple white desk on a white wall with a plant on the far right side" class="article-image">
                <p class="article-info">July 23, 2019 | 3 comments</p>
            </div>
        </article>

        <article class="article-recent">
            <div class="article-recent-main">
                <h2 class="article-title">How to keep your cooking simple </h2>
                <p class="article-body">Food is a very important part of everyone's life. If you want to be healthy, you
                    have to eat healthy. One of the easiest ways to do that is to keep your cooking nice and simple.</p>
                <a href="#" class="article-read-more">CONTINUE READING</a>
            </div>
            <div class="article-recent-secondary">
                <img src="{% static 'img/food.jpg' %}" alt="two dumplings on a wood plate with chopsticks"
                    class="article-image">
                <p class="article-info">July 19, 2019 | 3 comments</p>
            </div>
        </article>

        <article class="article-recent">
            <div class="article-recent-main">
                <h2 class="article-title">Simplicity and work </h2>
                <p class="article-body">Work is often a major source of stress. People get frustrated, it ruins their
                    relationship with others and it leads to burnout. By keeping your work life as simple as possible,
                    it will help balance everything out.</p>
                <a href="#" class="article-read-more">CONTINUE READING</a>
            </div>
            <div class="article-recent-secondary">
                <img src="{% static 'img/work.jpg' %}" alt="a chair white chair at a white desk on a white wall"
                    class="article-image">
                <p class="article-info">July 12, 2019 | 3 comments</p>
            </div>
        </article>

        <article class="article-recent">
            <div class="article-recent-main">
                <h2 class="article-title">Simple decorations</h2>
                <p class="article-body">A home isn't a home until you've decorated a little. People either don't
                    decorate, or they go overboard and it doesn't have the impact they were hoping for. Staying simple
                    will help draw the eye where you want it to and make things pop like never before.</p>
                <a href="#" class="article-read-more">CONTINUE READING</a>
            </div>
            <div class="article-recent-secondary">
                <img src="{% static 'img/deco.jpg' %}" alt="a green plant in a clear, round vase with water in it"
                    class="article-image">
                <p class="article-info">July 3, 2019 | 3 comments</p>
            </div>
        </article>
    </main>

    <aside class="sidebar">

        <div class="sidebar-widget">
            <h2 class="widget-title">ABOUT ME</h2>
            <img src="{% static 'img/about-me.jpg' %}" alt="john doe" class="widget-image">
            <p class="widget-body">I find life better, and I'm happier, when things are nice and simple.</p>
        </div>

        <div class="sidebar-widget">
            <h2 class="widget-title">RECENT POSTS</h2>
            <div class="widget-recent-post">
                <h3 class="widget-recent-post-title">Keeping cooking simple</h3>
                <img src="{% static 'img/food.jpg' %}" alt="two dumplings on a wood plate with chopsticks"
                    class="widget-image">
            </div>
            <div class="widget-recent-post">
                <h3 class="widget-recent-post-title">Simplicity and work</h3>
                <img src="{% static 'img/work.jpg' %}" alt="a chair white chair at a white desk on a white wall"
                    class="widget-image">
            </div>
            <div class="widget-recent-post">
                <h3 class="widget-recent-post-title">Simple decorations</h3>
                <img src="{% static 'img/deco.jpg' %}" alt="a green plant in a clear, round vase with water in it"
                    class="widget-image">
            </div>
        </div>

    </aside>

</div>


<footer>
    <p><strong>Living the Simple Life</strong></p>
    <p>Copyright 2019</p>
</footer>




{% endblock %}